import AuthProvider from "@/components/AuthProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Inter, Gaegu } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const gaegu = Gaegu({ 
  weight: '400',
  subsets: ["latin"] });

export const metadata = {
  title: "hotseat ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3327430877137663"
     crossorigin="anonymous"></script>
      </head>
      <ThemeProvider>
        <AuthProvider>
          <body className={inter.className}>{children}</body>
        </AuthProvider>
      </ThemeProvider>
    </html>
  );
}
