import ClientLayout from "@/components/ClientLayout";
import { Lexend, Gaegu } from "next/font/google";
import "./globals.css";

const lexend = Lexend({
  subsets: ["latin"],
  variable: '--font-lexend'
});

const gaegu = Gaegu({
  weight: '400',
  subsets: ["latin"],
  variable: '--font-gaegu'
});

export const metadata = {
  title: "hotseat ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${lexend.variable} ${gaegu.variable} min-h-screen`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
